### ISSUE TITLE
github-actions or dependabot PRs should not be added to board

### ISSUE THREAD

**Issue by emteknetnz** [silverstripe/gha-add-pr-to-project#7]
Current the action contains a hardcoded list of CMS squad members who should not have their PRs added to the board

We should also exclude PRs created by bots namely github-actions as well as dependabot

## Acceptance criteria
- PRs created by `dependabot[bot]` and `github-actions[bot]` are not added to the project board
- Any PRs from those user agents currently on the board are removed from the board (but not closed)

## PRs
- https://github.com/silverstripe/gha-add-pr-to-project/pull/11

**Comment by ChloeSartorelli** [comment]
PR merged
